"""add partial unique index for active session

Revision ID: ab80cbdd8b59
Revises: c88cfc521502
Create Date: 2026-09-30 19:59:57.426494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab80cbdd8b59'
down_revision: Union[str, Sequence[str], None] = 'c88cfc521502'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_only_one_active_session', 'sessions', [sa.text('(1)')], unique=True, postgresql_where=sa.text('finished_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_only_one_active_session', table_name='sessions', postgresql_where=sa.text('finished_at IS NULL'))
    # ### end Alembic commands ###
